SUPABASE_URL = "https://hiiinauqhobwuwkudqwn.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpaWluYXVxaG9id3V3a3VkcXduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5OTU2NDMsImV4cCI6MjA1NjU3MTY0M30.FVbDsZ9HTBhaklUngZuic2BlwRvAjFJevjznV4RYjRk"
